# Site settings
title: Persistence Of Memory
email: shuvambosana0705@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hacks about life apart from programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://shuvam07.github.io" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000"
twitter_username: 
github_username:  shuvam07

# Build settings
markdown: kramdown
